version: '3'

services:
  proxy:
    container_name: proxy
    #build: './services/loadbalancer'
    build: '.'
    stdin_open: true
    tty: true
    ports:
      - 8080
    # depends_on: 
    #   - app01
    #   - app02